name: hello-actions2
run-name: hello ${{ github.actor }} 2
on: [push]

jobs:
  Run Editor Tests:
    name: Run Editor Tests job
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: false # TODO: Review
        
      # Cache
      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-UnityCICDTest1
          restore-keys: |
            Library-
      
      # Test
      - name: Run Editor Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: editmode
      
      #Output
      - uses: actions/upload-artifact@v4
        with:
          name: Test results
          path: artifacts
      